version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "auth"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ia9egdg91dqr"
s3_prefix = "auth"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
